version: '3.1'

services:

  wordpress:
    container_name: wordpress
    depends_on:
      - mysql
    image: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: $MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./databases.sql:/home/databases.sql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
