version: '3.1'

services:

  wordpress:
    container_name: $WORDPRESS_CONTAINER_NAME
    depends_on:
      - mysql
    image: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: $MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
  mysql:
    container_name: $MYSQL_CONTAINER_NAME
    image: mysql:5.6
    build:
      context: .
      dockerfile: mysql.dockerfile
    volumes:
      - ./database:/home/database/
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
